#!/usr/bin/env bash
# Author: Louie Chen <louie23 _at_ lavabit com>
# License: GPL-3+
# Description: This script will generate knockd one_time_sequences file

line=10
port_min=1024
port_max=65535
item_min=3
item_max=7
udp=1

while [ -n "$1" ]
do
	case "$1" in
		-h)
			echo "-h: this help"
			echo "-l|--lines: how many lines to generate"
			echo "-nu|--no-udp: turn off udp"
			echo "-s|--port-min: the minimum port range"
			echo "-b|--port-max: the maximum port range"
			echo "-x|--item-min: the minimum item range"
			echo "-y|--item-max: the maximum item range"
			exit 0
			;;
		-l|--lines)
			shift
			line=$1
			shift
			;;
		-s|--port-min)
			shift
			port_min=$1
			shift
			;;
		-b|--port-max)
			shift
			port_max=$1
			shift
			;;
		-x|--item-min)
			shift
			item_min=$1
			shift
			;;
		-y|--item-max)
			shift
			item_max=$1
			shift
			;;
		-nu|--no-udp)
			shift
			udp=0
			;;
		*)
			;;
	esac
done

count=$line

if [ "$port_max" -lt "$port_min" ]
then
	echo "--port-max must large than --port-min"
	exit 0
fi

if [ "$item_max" -lt "$item_min" ]
then
	echo "--item-max must large than --item-min"
	exit 0
fi

while [ $count -gt "0" ]
do
	times=`shuf -i$item_min-$item_max -n1`
	for (( i = 1; i < $times; i++ ))
    do
		number=`shuf -i$port_min-$port_max -n1`
        if [ $udp == 0 ]
        then
            echo -n "T:$number "
        fi
		if [ $udp == 1 ]
        then
			tcpORudp=`shuf -i1-2 -n1`
            if [ "$tcpORudp" == 1 ]
            then
				echo -n "T:$number "
			fi
			if [ "$tcpORudp" == 2 ]
            then
				echo -n "U:$number "
			fi
		fi
	done
	count=$(($count-1))
	echo
done
